# Practice of Numpy Library


In [1]:
import numpy as np # in which we import numpy as set variable is np we can set any variable

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(a) # it's print the array in matrix format.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(a.dtype) # it shows the datatype of an array

int32


In [5]:
print(a.shape) # it prints the shape of array 

(3, 3)


In [6]:
print(a.reshape) # when we use reshape command for array it change temporary

<built-in method reshape of numpy.ndarray object at 0x0000015BCCCFDD50>


In [7]:
print(a.resize) # when we use this command it's change the array size permanently
a

<built-in method resize of numpy.ndarray object at 0x0000015BCCCFDD50>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(a.ndim) # this command is used for finding the dimension of an array

2


In [9]:
np.zeros((2,2))# using this command we can generate an array with the values of zeros for that we have to pass the size of an array 

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones((2,3)) # same like as zeros  method change is we print the values by using the ones method 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.full((2,2),7) #if we want to print the values other than 0 & 1 then we can use full function with the parameter of size and values of an array

array([[7, 7],
       [7, 7]])

In [12]:
np.random.random((3,4)) # if we want to print the random values we can use random  method for print the random values

array([[0.82752362, 0.9314029 , 0.20638406, 0.69878342],
       [0.21824317, 0.93623251, 0.32038989, 0.59826861],
       [0.20091069, 0.40711657, 0.71997084, 0.80179746]])

In [13]:
np.random.randint(0,10,(2,3)) # for printing the 

array([[3, 3, 3],
       [2, 8, 5]])

In [14]:
np.arange(0,40,3)
# if we want to create an array by using method we can use 'arange' method for that
# syntax is - np.arange(intital point,end point,and diffrence betwwen the values)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [15]:
a=np.linspace(0,5,5)
print(a)
#by using the 'linspace' method we make equal parts of the given range to linspace method
# another example is-
b=np.linspace(4,9,5)
print(b)

[0.   1.25 2.5  3.75 5.  ]
[4.   5.25 6.5  7.75 9.  ]


# Mathematical operatin  of two array

# Here size of an array should be same

In [16]:
import sys
x=np.array([1,2,4,3,5])
y=np.array([6,7,8,9,0])

c=print(x+y)
d=print(x-y)
e=print(x*y)
f=print(x/y)
# in this cell we see the mathematical operation of two array 

[ 7  9 12 12  5]
[-5 -5 -4 -6  5]
[ 6 14 32 27  0]
[0.16666667 0.28571429 0.5        0.33333333        inf]


C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  


In [17]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.sum((a,b)))
print()
c=print(a,b)
print()
d=print(a+b)
# Here observe the both the method in first method we use sum() method for addition of two array and it gives single output
# But when use the plus(+) operator for addition of two array it gives output in array format 

36

[[1 2]
 [3 4]] [[5 6]
 [7 8]]

[[ 6  8]
 [10 12]]


# here we are we can find the minimum and maxmimum values form the given array

In [18]:
x=np.array([[5,6],[3,4],[7,8]])
y=np.array([[1,2],[3,4],[5,6]])
#print(x)
#print(y)
print('The minimum value of x array: ',np.min(x))
print("the maximum value of x array: ",np.max(x))
print("the maximum value of y array: ",np.max(y))
print("the minimum value of y array: ",np.min(y))

The minimum value of x array:  3
the maximum value of x array:  8
the maximum value of y array:  6
the minimum value of y array:  1
